blank_issues_enabled: false
contact_links:
  - name: 💁 Discussion
    url: https://blog.csdn.net/HJS1453100406
    about: 'This issue tracker is not for support questions. Leave a comment on the discussion board if you need help.'
